pipeline {
    agent { node {label 'agent-1'} }
    options{
        ansiColor('xterm')
    }

    stages {
        stage('init') {
            steps {
              sh '''
                cd roboshop-infra-standard/01-vpc 
                pwd
                terraform init
              '''
            }
        }
        stage('plan') {
            steps {
              sh ''' 
                cd roboshop-infra-standard/01-vpc 
                pwd
                terraform plan
              '''}
        }      
    }

}