pipeline {
    agent { node {label 'agent-1'} }

    stages {
        stage('init') {
            steps {
              sh ''' 
                pwd
                terraform init
              '''
            }
        }
        stage('plan') {
            steps {
              sh ''' 
                pwd
                terraform plan
              '''}
        }      
    }

}