- name: testing loops in ansible
  hosts: localhost
  tasks:
    - name: printing names using loops
      ansible.builtin.debug:
        msg: "hi,{{item}}"
      loop:
        - raj
        - kumar
        - mikkili
